const DEPARTMENTS = ["FACILITIES", "IT", "SECURITY", "HR"];
const PRIORITIES = ["LOW", "MEDIUM", "HIGH"];
const STATUSES = ["NEW", "IN_PROGRESS", "BLOCKED", "DONE"];

const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  NOT_FOUND: "NOT_FOUND",
  INVALID_TRANSITION: "INVALID_TRANSITION",
  CONFLICT: "CONFLICT",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",
  INTERNAL_ERROR: "INTERNAL_ERROR"
};

const TRANSITIONS = {
  NEW: ["IN_PROGRESS"],
  IN_PROGRESS: ["BLOCKED", "DONE"],
  BLOCKED: ["IN_PROGRESS"],
  DONE: []
};

module.exports = { DEPARTMENTS, PRIORITIES, STATUSES, ERROR_CODES, TRANSITIONS };